# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7995f764be124f34f3501c8ae05240fd8bedcec46d27ddba40d96f4783dc8d55a3ea1f468dc9c4bbf8b52091a7fb40dbb1f3a64c006e9eef9039d406485f0e8a

test:
  secret_key_base: 970797224a22153ea6d0e1dad1fff9d207c1718ac45c8c0039fe41b3cb0bc511cb23d8728f08189451fcc1c715453e4484327789402beda6e465c7385ff9e2ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
